### PR TITLE
Fix build on linux with libmagic

### PR DESCRIPTION
**Pull request by wataash**

### CODE REVIEW

**Comment by whoozle** [comment]
Your fix has broken Travis build :)

**Comment by wataash** [comment]
Yup, as expected :)
I just wanted to show you that this #181 can be reproduced on an environment other than my Ubuntu.
I'll fix it in the next commit.

Sorry for my slow activity. Feel free to close this PR if you fix it!

**Comment by whoozle** [comment]
You can set it manually using ui or by editting cmakecache file, it's not
something you need everyday

**Comment by wataash** [comment]
Okay.

**Comment by whoozle** [comment]
thanks a lot!

**Pull request merged**
