### PR TITLE
Generate AppImage on Travis CI and upload to GitHub Releases

### LINKED ISSUE #171: Appimage for Linux distribution
Would be great if you could provide a binary build in appimage format for linux users so they dont have to compile releases from source. Apps like Krita, Kdenlive, and OpenShot do so.

You can find information about how to do so here - https://github.com/AppImage/AppImageKit/

### PR DESCRIPTION
**Pull request by probonopd**
This PR, when merged, will compile this application on [Travis CI](https://travis-ci.org/) upon each `git push`, and upload an [AppImage](http://appimage.org/) to your GitHub Releases page. Closes #171.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

__PLEASE NOTE:__ For this to work, you need to enable Travis CI for your repository as [described here](https://travis-ci.org/getting_started) __prior to merging this__, if you haven't already done so. Also, You need to set up `GITHUB_TOKEN` in Travis CI for this to work; please see https://github.com/probonopd/uploadtool.
If you would like to see only one entry for the Pull Request in your project's history, then please enable [this GitHub functionality](https://help.github.com/articles/configuring-commit-squashing-for-pull-requests/) on your repo. It allows you to squash (combine) the commits when merging.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

### CODE REVIEW

**Comment by probonopd** [comment]
A build is available on https://github.com/probonopd/android-file-transfer-linux/releases

I have tested it with an Android MTP device and was able to successfully download a file to Ubuntu 17.10 using it.

**Comment by whoozle** [comment]
I'm sorry, I've missed your PR completely :(

**Comment by whoozle** [comment]
Thanks a lot! it looks like great addition to the project indeed!

**Comment by probonopd** [comment]
Please note: As indicated in the log file, `$GITHUB_TOKEN` missing, please set it in the Travis CI settings of this project. You can get one from https://github.com/settings/tokens. Then the build artifacts will be uploaded to GitHub Releases.

**Pull request merged**
