### PR TITLE
enable fuse in travis build script for mac

### PR DESCRIPTION
**Pull request by yurikoles**

### CODE REVIEW

**Comment by whoozle** [comment]
can you remove default option tweaking in CMakeLists.txt instead of passing -DBUILD_FUSE to cmake? 
original option was removed, because it failed builds with osxfuse installed, but now it's fine to have it enabled by default.

**Comment by whoozle** [comment]
and travis has failed with
```Error: No available formula with the name "cask/osxfuse" ```

**Comment by yurikoles** [comment]
done

**Comment by yurikoles** [comment]
@whoozle done!

**Comment by yurikoles** [comment]
Yes, create please.

**Comment by yurikoles** [comment]
@whoozle tag please.

**Comment by yurikoles** [comment]
For now, I had sent a [PR](https://github.com/Homebrew/homebrew-cask-versions/pull/6525) for nightly

**Comment by whoozle** [comment]
tagged v3.7! sorry, completed forgot it

**Comment by yurikoles** [comment]
and [PR](https://github.com/Homebrew/homebrew-cask/pull/54762) for stable

**Pull request merged**
