### PR TITLE
fix macOS CI

### PR DESCRIPTION
**Pull request by yurikoles**
Signed-off-by: Yurii Kolesnykov <root@yurikoles.com>

### CODE REVIEW

**Comment by whoozle** [comment]
Thank you very much. It's still failing though, couldn't find the icons for MacOSX :)

**Comment by whoozle** [comment]
Sorry for the delay, big thanks for fixing macosx CI up!!

**Comment by yurikoles** [comment]
In fact, I didn't finish it, and It was still failing.

**Comment by whoozle** [comment]
ops, sorry, I'll revert it now, and you can reopen it at any time! :)

**Comment by yurikoles** [comment]
I forgot to mention that
>Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

Please migrate project to it.

**Pull request merged**
