### PR TITLE
Fix `--device-list` asking for argument

### PR DESCRIPTION
**Pull request by ammgws**
Unless I've misunderstood, `--device-list` shouldn't ask for an argument

### CODE REVIEW

**Comment by ammgws** [comment]
@whoozle Would it be possible to tag a new release so that this (and presumably other fixes?) can make it into downstream packages?

**Comment by whoozle** [comment]
oh dear, it's been 3 years since the last release, I'll do it ASAP

**Comment by whoozle** [comment]
Sorry, don't download it just yet. Turned out GitHub actions don't work for tags

**Comment by whoozle** [comment]
It's all good now, Ubuntu is live and release artefacts are attached as well. 

https://github.com/whoozle/android-file-transfer-linux/releases/tag/v4.3

**Pull request merged**
